---
# https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
# yaml-language-server: $schema=https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.schema.json
global:
  leaderElection:
    namespace: cert-manager
  priorityClassName: platform
  commonLabels:
replicaCount: 2
podLabels:
  networking/allow-egress-internet: "true"
  networking/allow-ingress-prometheus: "true"
  networking/allow-cluster-egress: "true"
namespace: cert-manager
installCRDs: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
webhook:
  replicaCount: 2
  podLabels:
    networking/allow-ingress-prometheus: "true"
    networking/allow-cluster-egress: "true"
  networkPolicy:
    enabled: false
cainjector:
  replicaCount: 2
  podLabels:
    networking/allow-ingress-prometheus: "true"
    networking/allow-cluster-egress: "true"
