---
priorityClassName: platform
resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    memory: 256Mi

metrics:
  enabled: true

serviceMonitor:
  enabled: true

grafanaDashboard:
  enabled: true

prometheusRules:
  enabled: false
  additionalLabels:
    release: kube-prometheus-stack
