---
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
crds:
  enabled: false
cleanPrometheusOperatorObjectNames: true
alertmanager:
  enabled: true
  templateFiles:
    discord.tmpl: |-
      {{ define "homelab.discord.title" -}}
      {{ if eq .Status "firing" }}🔥 FIRING{{ else }}✅ RESOLVED{{ end }}{{ if gt (len .Alerts.Firing) 1 }} ×{{ len .Alerts.Firing }}{{ end }}: {{ .CommonLabels.alertname }} [{{ .CommonLabels.severity | toUpper }}]
      {{- end }}

      {{ define "homelab.discord.message" -}}
      {{ range $i, $a := .Alerts -}}
      {{ if gt $i 0 }}─────────────────
      {{ end -}}
      {{ if $a.Annotations.summary }}**{{ $a.Annotations.summary }}**
      {{ end -}}
      {{ if $a.Annotations.description }}{{ $a.Annotations.description | reReplaceAll " on cluster [^.]*\\." "" }}
      {{ end -}}
      {{ if or $a.Labels.namespace $a.Labels.deployment $a.Labels.statefulset $a.Labels.daemonset $a.Labels.pod $a.Labels.kubernetes_node -}}
      **Context:** {{ if $a.Labels.namespace }}`ns/{{ $a.Labels.namespace }}`{{ end }}{{ if $a.Labels.deployment }} `deploy/{{ $a.Labels.deployment }}`{{ end }}{{ if $a.Labels.statefulset }} `sts/{{ $a.Labels.statefulset }}`{{ end }}{{ if $a.Labels.daemonset }} `ds/{{ $a.Labels.daemonset }}`{{ end }}{{ if and $a.Labels.pod (not (or $a.Labels.deployment $a.Labels.statefulset $a.Labels.daemonset)) }} `pod/{{ $a.Labels.pod }}`{{ end }}{{ if $a.Labels.kubernetes_node }} `node/{{ $a.Labels.kubernetes_node }}`{{ end }}
      {{ end -}}
      {{ if $a.Annotations.runbook_url }}[📖 Runbook]({{ $a.Annotations.runbook_url }})
      {{ end -}}
      {{ end -}}
      {{- end }}
  alertmanagerSpec:
    priorityClassName: platform
    podMetadata:
      labels:
        networking/allow-egress-internet: "true"
    replicas: ${default_replica_count}
    alertmanagerConfiguration:
      name: alertmanager
      global:
        resolveTimeout: 5m
    externalUrl: https://alertmanager.${external_domain}
    templates:
      - secret:
          name: alertmanager-kube-prometheus-stack
          key: discord.tmpl
    storage:
      emptyDir: { }
kubeApiServer:
  serviceMonitor:
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
    metricRelabelings:
      - action: drop
        sourceLabels: [__name__]
        regex: 'apiserver_(request_body_size_bytes|watch_list_duration_seconds|watch_cache_read_wait_seconds|response_sizes|watch_events_sizes|request_sli_duration_seconds)_bucket|etcd_request_duration_seconds_bucket'
kubeScheduler:
  service:
    selector:
      k8s-app: kube-scheduler
kubeControllerManager: &kubeControllerManager
  service:
    selector:
      k8s-app: kube-controller-manager
kubeEtcd:
  <<: *kubeControllerManager  # etcd runs on control plane nodes
kubeProxy:
  enabled: false
prometheus:
  ingress:
    enabled: false
  prometheusSpec:
    priorityClassName: platform
    replicas: 1
    podMetadata:
      labels:
        networking/allow-ingress-internal: "true"
    externalLabels:
      prometheus_source: ${cluster_name}
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: { }
    scrapeConfigSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    enableAdminAPI: true
    walCompression: true
    enableFeatures:
      - memory-snapshot-on-shutdown
    retention: 7d
    retentionSize: ${prometheus_retention_size}
    queryTimeout: 5m
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 8Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: fast
          resources:
            requests:
              storage: ${prometheus_volume_size}
prometheus-node-exporter:
  fullnameOverride: node-exporter
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: ["__meta_kubernetes_pod_node_name"]
          targetLabel: kubernetes_node
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: ["__meta_kubernetes_pod_node_name"]
          targetLabel: instance
kube-state-metrics:
  fullnameOverride: kube-state-metrics
  metricLabelsAllowlist:
    - pods=[*]
    - deployments=[*]
    - persistentvolumeclaims=[*]
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: ["__meta_kubernetes_pod_node_name"]
          targetLabel: kubernetes_node
grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      annotations:
        grafana_folder: "Kubernetes"
defaultRules:
  create: true
  disabled:
    KubeClientCertificateExpiration: true
    NodeDiskIOSaturation: true
additionalPrometheusRulesMap:
  node-disk-rules:
    groups:
      - name: node-disk
        rules:
          - alert: NodeDiskIOSaturation
            annotations:
              description: |
                Disk IO queue (aqu-sq) is high on {{ $labels.device }} at {{ $labels.instance }}, has been above 10 for the last 30 minutes, is currently at {{ printf "%.2f" $value }}.
                This symptom might indicate disk saturation.
              runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodediskiosaturation
              summary: Disk IO queue is high.
            expr: |
              (
                rate(node_disk_io_time_weighted_seconds_total{job="node-exporter", device=~"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)"}[5m])
              * on(instance, device) group_left()
                node_disk_info{model!="VIRTUAL-DISK"}
              ) > 10
            for: 30m
            labels:
              severity: warning
  oom-rules:
    groups:
      - name: oom
        rules:
          - alert: OomKilled
            annotations:
              summary: Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
            expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
            labels:
              severity: critical

  custom-apiserver:
    groups:
      - name: kubernetes-system-apiserver
        rules:
          - alert: KubeClientCertificateExpiration
            annotations:
              description: A client certificate used to authenticate to kubernetes apiserver
                is expiring in less than 7.0 days on cluster {{ $labels.cluster }}.
              runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclientcertificateexpiration
              summary: Client certificate is about to expire.
            expr: |-
              histogram_quantile(0.05, sum without (namespace, service, endpoint) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 604800
              and
              on (job, cluster, instance) apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0
            for: 5m
            labels:
              severity: warning
          - alert: KubeClientCertificateExpiration
            annotations:
              description: A client certificate used to authenticate to kubernetes apiserver
                is expiring in less than 24.0 hours on cluster {{ $labels.cluster }}.
              runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclientcertificateexpiration
              summary: Client certificate is about to expire.
            expr: |-
              histogram_quantile(0.05, sum without (namespace, service, endpoint) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 86400
              and
              on (job, cluster, instance) apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0
            for: 5m
            labels:
              severity: critical
