---
# https://raw.githubusercontent.com/stakater/Reloader/master/deployments/kubernetes/chart/reloader/values.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/stakater/Reloader/master/deployments/kubernetes/chart/reloader/values.schema.json

reloader:
  deployment:
    priorityClassName: platform
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
  podMonitor:
    enabled: true
  reloadStrategy: annotations
