---
# https://raw.githubusercontent.com/mittwald/kubernetes-replicator/master/deploy/helm-chart/kubernetes-replicator/values.yaml
priorityClassName: platform
image:
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 10m
    memory: 100Mi
