---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
# https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
controllers:
  bazarr:
    type: deployment

    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/bazarr
          tag: "${bazarr_version}"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 1Gi
        probes:
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/system/ping
                port: 6767
              initialDelaySeconds: 5
              periodSeconds: 5
              failureThreshold: 30
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/system/ping
                port: 6767
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/system/ping
                port: 6767
              periodSeconds: 10

service:
  app:
    controller: bazarr
    ports:
      http:
        port: 6767

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: fast
    advancedMounts:
      bazarr:
        app:
          - path: /config
  media:
    type: persistentVolumeClaim
    existingClaim: media-library
    advancedMounts:
      bazarr:
        app:
          - path: /media
  tmp:
    type: emptyDir
    advancedMounts:
      bazarr:
        app:
          - path: /tmp
