---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/values.schema.json
controllers:
  booter:
    type: deployment

    containers:
      app:
        image:
          repository: ghcr.io/siderolabs/booter
          tag: "${booter_version}"
        args:
          - --talos-version=${talos_version}
          - --schematic-id=${talos_pxe_schematic_id}
          - --api-advertise-address=${booter_ip}
          - --disable-dhcp-proxy
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
            add:
              - NET_BIND_SERVICE
          seccompProfile:
            type: RuntimeDefault

defaultPodOptions:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: booter
          topologyKey: kubernetes.io/hostname

service:
  app:
    controller: booter
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: ${booter_ip}
    ports:
      tftp:
        port: 69
        protocol: UDP
      http:
        port: 50084
        protocol: TCP
