---
# https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/charts/external-dns/values.schema.json
provider:
  name: cloudflare

sources:
  - gateway-httproute
  - gateway

domainFilters:
  - ${external_domain}

policy: sync

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  seccompProfile:
    type: RuntimeDefault

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: token

serviceMonitor:
  enabled: true
  interval: 1m

resources:
  requests:
    cpu: 10m
    memory: 64Mi
