---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
# https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
controllers:
  it-tools:
    type: deployment
    replicas: 1

    containers:
      app:
        image:
          repository: ghcr.io/corentinth/it-tools
          tag: "${it_tools_version}"
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 5
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 5
              periodSeconds: 10

service:
  app:
    controller: it-tools
    ports:
      http:
        port: 80
