---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
# https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
controllers:
  jellyseerr:
    type: deployment

    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    containers:
      app:
        image:
          repository: ghcr.io/seerr-team/seerr
          # renovate: datasource=docker depName=ghcr.io/seerr-team/seerr
          tag: 3.0.1
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop: [ALL]
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 512Mi
        probes:
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/status
                port: 5055
              initialDelaySeconds: 5
              periodSeconds: 5
              failureThreshold: 30
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/status
                port: 5055
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/status
                port: 5055
              periodSeconds: 10

service:
  app:
    controller: jellyseerr
    ports:
      http:
        port: 5055

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: fast
    advancedMounts:
      jellyseerr:
        app:
          - path: /app/config
