---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
# https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
controllers:
  jfa-go:
    type: deployment

    pod:
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault

    containers:
      app:
        image:
          repository: hrfee/jfa-go
          tag: latest
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop: [ALL]
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
        probes:
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 8056
              initialDelaySeconds: 10
              periodSeconds: 5
              failureThreshold: 30
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 8056
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 8056
              periodSeconds: 10

service:
  app:
    controller: jfa-go
    ports:
      http:
        port: 8056

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: fast
    advancedMounts:
      jfa-go:
        app:
          - path: /data
