---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: cluster-values
    namespace: flux-system
    behavior: create
    files:
      - zipline.yaml=zipline.yaml
      - immich.yaml=immich.yaml
      - authelia.yaml=authelia.yaml
      - lldap.yaml=lldap.yaml
      - valheim.yaml=valheim.yaml
      - factorio.yaml=factorio.yaml
      - satisfactory.yaml=satisfactory.yaml
      - minecraft.yaml=minecraft.yaml
      - pxe-boot.yaml=pxe-boot.yaml
      - qbittorrent.yaml=qbittorrent.yaml
      - prowlarr.yaml=prowlarr.yaml
      - sonarr.yaml=sonarr.yaml
      - radarr.yaml=radarr.yaml
      - bazarr.yaml=bazarr.yaml
      - jellyfin.yaml=jellyfin.yaml
      - jellyseerr.yaml=jellyseerr.yaml
      - vaultwarden.yaml=vaultwarden.yaml
      - exportarr.yaml=exportarr.yaml
