---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
# https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
controllers:
  sonarr:
    type: deployment

    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    containers:
      app:
        image:
          repository: ghcr.io/home-operations/sonarr
          # renovate: datasource=docker depName=ghcr.io/home-operations/sonarr
          tag: 4.0.16.2946
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 1Gi
        probes:
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 8989
              initialDelaySeconds: 5
              periodSeconds: 5
              failureThreshold: 30
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 8989
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 8989
              periodSeconds: 10

service:
  app:
    controller: sonarr
    ports:
      http:
        port: 8989

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: fast
    advancedMounts:
      sonarr:
        app:
          - path: /config
  media:
    type: persistentVolumeClaim
    existingClaim: media-library
    advancedMounts:
      sonarr:
        app:
          - path: /media
