---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
# https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
controllers:
  tika:
    type: deployment
    replicas: 1

    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 35002
        runAsGroup: 35002
        seccompProfile:
          type: RuntimeDefault

    containers:
      app:
        image:
          repository: apache/tika
          # renovate: datasource=docker depName=apache-tika packageName=apache/tika
          tag: "${tika_version}"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop: [ALL]
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            memory: 2Gi
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /tika
                port: 9998
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /tika
                port: 9998
              periodSeconds: 10

service:
  app:
    controller: tika
    ports:
      http:
        port: 9998
