---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-rules.yaml
  - backup/
  - recurring-jobs/backup-daily.yaml
  - recurring-jobs/backup-frequent.yaml
  - recurring-jobs/snapshot-daily.yaml
  - recurring-jobs/snapshot-frequent.yaml
  - recurring-jobs/snapshot-minimal.yaml
  - recurring-jobs/filesystem-trim-daily.yaml
  - routes/
  - storage-classes/ephemeral.yaml
  - storage-classes/fast-local.yaml
  - storage-classes/fast-nr.yaml
  - storage-classes/fast.yaml
  - storage-classes/slow.yaml
