---
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-platform
  namespace: velero
spec:
  # Automatically selects the most recent successful backup from this schedule
  scheduleName: platform
  restorePVs: true
  includedNamespaces:
    - garage
    - database
