---
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-default
  namespace: velero
spec:
  # Automatically selects the most recent successful backup from this schedule
  scheduleName: default
  existingResourcePolicy: update
