---
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-oidc-client-secret
  namespace: miniflux
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/miniflux-oidc-client-secret
data: { }
