---
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-admin-credentials
  namespace: miniflux
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
type: Opaque
stringData:
  username: admin
