---
apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
  namespace: sure
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secret-key-base
    secret-generator.v1.mittwald.de/length: "128"
    secret-generator.v1.mittwald.de/encoding: hex
data: { }
