---
apiVersion: v1
kind: Secret
metadata:
  name: sure-db-credentials
  namespace: sure
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/sure-role-password
type: Opaque
data: { }
