---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: cluster-config-kustomizations
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "10m"
spec:
  inputs:
    - name: authelia-prereqs
      path: kubernetes/clusters/live/config/authelia-prereqs
      dependsOn: [platform, external-secrets-stores]
    - name: authelia-config
      path: kubernetes/clusters/live/config/authelia
      dependsOn: [authelia, lldap, canary-checker, kube-prometheus-stack]
    - name: media-prereqs
      path: kubernetes/clusters/live/config/media-prereqs
      dependsOn: [platform, secret-generator, external-secrets-stores]
    - name: media-config
      path: kubernetes/clusters/live/config/media
      dependsOn: [bazarr, jellyfin-exporter, jellyfin, jellyseerr, sonarr, radarr, prowlarr, qbittorrent, exportarr, canary-checker, kube-prometheus-stack]
    - name: ai-prereqs
      path: kubernetes/clusters/live/config/ai-prereqs
      dependsOn: [platform, secret-generator, external-secrets-stores]
    - name: ai-config
      path: kubernetes/clusters/live/config/ai
      dependsOn: [open-webui, ollama, canary-checker, kube-prometheus-stack]
  resourcesTemplate: |
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << inputs.name >>
      namespace: flux-system
    spec:
      <<- if inputs.dependsOn >>
      dependsOn:
      <<- range $dep := inputs.dependsOn >>
        - name: << $dep >>
      <<- end >>
      <<- end >>
      interval: 10m
      path: << inputs.path >>
      prune: true
      sourceRef:
        kind: ${source_kind}
        name: flux-system
      postBuild:
        substituteFrom:
          - kind: ConfigMap
            name: cluster-vars
            optional: false
          - kind: ConfigMap
            name: platform-versions
            optional: true
