---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zipline
  - immich
  - valheim
  - factorio
  - satisfactory
  - pxe-boot
  - paperless
  - silences
  - cluster-config-resourceset.yaml
