---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - it-tools
  - zipline
  - vaultwarden
  - immich
  - valheim
  - factorio
  - satisfactory
  - minecraft
  - pxe-boot
  - tandoor
  - paperless
  - firefly
  - homepage
  - longhorn-snapshots
  - velero
  - silences
  - cluster-config-resourceset.yaml
