---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-cookie-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: cookie-secret
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
stringData: { }
