---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-oauth-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: github-oauth-credentials
  data:
    - secretKey: client-id
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/github-oauth-proxy
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/github-oauth-proxy
        property: client-secret
