---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github-oauth-credentials.yaml
  - cookie-secret.yaml
  - oauth2-proxy-route.yaml
  - oauth2-proxy-canary.yaml
