---
apiVersion: v1
kind: Secret
metadata:
  name: fusion-oidc-client-secret
  namespace: fusion
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/fusion-oidc-client-secret
data: { }
