---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fusion-data
  namespace: fusion
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 1Gi
