---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: default
  namespace: velero
spec:
  schedule: "0 2 * * 0"
  useOwnerReferencesInBackup: false
  template:
    storageLocation: aws
    volumeSnapshotLocations:
      - csi
    snapshotMoveData: true
    csiSnapshotTimeout: 30m0s
    ttl: 672h0m0s
    includedNamespaces:
      - immich
      - satisfactory
      - valheim
      - factorio
      - minecraft
      - paperless
      - media
      - vaultwarden
