---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: default
  namespace: velero
spec:
  schedule: "0 */6 * * *"
  useOwnerReferencesInBackup: false
  template:
    storageLocation: aws
    volumeSnapshotLocations:
      - csi
    snapshotMoveData: true
    ttl: 168h0m0s
    includedNamespaces:
      - immich
      - satisfactory
      - valheim
      - factorio
      - minecraft
      - paperless
      - media
      - vaultwarden
