{
 "title": "Hardware Status",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(globalSystemStatus,service)"
    }
   },
   { "name": "kwh_price", "query": "0.18" }
  ]
 },
 "panels": [
  { "title": "Hardware Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(processorDeviceCoreCount{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(physicalDiskCapacityInMB{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sysUpTime{service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(amperageProbeReading{service=\"$service\",amperageProbeIndex=\"3\"}[$__range]) / 120 / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "systemPowerState{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "System Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemStateBatteryStatusCombined{service=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "powerSupplyStatus{service=\"$service\"}",
     "legendFormat": "PSU{{powerSupplyIndex}}"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperatureProbeStatus{service=\"$service\"}",
     "legendFormat": "Probe {{temperatureProbeIndex}}"
    }
   ]
  },
  {
   "title": "Drives",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "physicalDiskComponentStatus{service=\"$service\"}",
     "legendFormat": "Drive {{physicalDiskNumber}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(processorDeviceIndex{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memoryDeviceSize{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Amperage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amperageProbeReading{service=\"$service\"} > 20)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Electric Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(amperageProbeReading{service=\"$service\",amperageProbeIndex=\"3\"}[$__range]) / 120 / 1000 * $kwh_price)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Server temperature sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(temperatureProbeReading{service=\"$service\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{service=\"$service\"})",
     "legendFormat": "{{temperatureProbeLocationName}}"
    },
    {}
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Drives",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(physicalDiskCapacityInMB{service=\"$service\"}) + on (physicalDiskNumber) group_left(physicalDiskDisplayName) (physicalDiskDisplayName{service=\"$service\"}) + on (physicalDiskNumber) group_left(physicalDiskProductID) (physicalDiskProductID{service=\"$service\"})  + on (physicalDiskNumber) group_left(physicalDiskSerialNo) (physicalDiskSerialNo{service=\"$service\"})"
    },
    {
     "expr": "physicalDiskComponentStatus{service=\"$service\"}"
    }
   ]
  }
 ]
}