---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: admin-password
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
stringData:
  admin-user: admin
