---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ember-alerts
  namespace: ember
  labels:
    app.kubernetes.io/name: ember
    release: kube-prometheus-stack
spec:
  groups:
    - name: ember.rules
      rules:
        - alert: EmberDown
          expr: |
            kube_deployment_status_replicas_available{namespace="ember", deployment="ember"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Ember is down"
            description: "No available Ember replicas for 5 minutes."
