---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: zipline
  namespace: garage
spec:
  clusterRef:
    name: garage
  keyPermissions:
    - keyRef:
        name: zipline
        namespace: zipline
      read: true
      write: true
