---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: zipline
  namespace: zipline
spec:
  clusterRef:
    name: garage
    namespace: garage
  neverExpires: true
  bucketPermissions:
    - bucketRef:
        name: zipline
        namespace: garage
      read: true
      write: true
  secretTemplate:
    name: zipline-s3-credentials
