---
apiVersion: v1
kind: Secret
metadata:
  name: zipline-db-credentials
  namespace: zipline
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/zipline-role-password
type: kubernetes.io/basic-auth
data: { }
