---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: velero-s3-credentials
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .access_key_id }}
          aws_secret_access_key={{ .secret_access_key }}
  data:
    - secretKey: access_key_id
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/velero-s3-backup/access-key-id
    - secretKey: secret_access_key
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/velero-s3-backup/secret-access-key
