---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-db-credentials
  namespace: media
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-db-credentials
  namespace: media
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-db-credentials
  namespace: media
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: bazarr-db-credentials
  namespace: media
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyseerr-db-credentials
  namespace: media
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
data: { }
