---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-db-credentials
  namespace: media
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/sonarr-role-password
type: kubernetes.io/basic-auth
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-db-credentials
  namespace: media
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/radarr-role-password
type: kubernetes.io/basic-auth
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-db-credentials
  namespace: media
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/prowlarr-role-password
type: kubernetes.io/basic-auth
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: bazarr-db-credentials
  namespace: media
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/bazarr-role-password
type: kubernetes.io/basic-auth
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyseerr-db-credentials
  namespace: media
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/jellyseerr-role-password
type: kubernetes.io/basic-auth
data: { }
