---
apiVersion: v1
kind: Secret
metadata:
  name: jellyseerr-oidc-client-secret
  namespace: media
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/jellyseerr-oidc-client-secret
data: { }
