---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-01
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-02
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-03
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-04
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-05
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-06
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-07
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-08
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-09
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-10
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-media
  resources:
    requests:
      storage: 10Ti
