---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
  namespace: media
  annotations:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast
  resources:
    requests:
      storage: 1Ti
