---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow-nb
  resources:
    requests:
      storage: 10Ti
