---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast-ephemeral
  resources:
    requests:
      storage: 250Gi
