---
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-credentials
  namespace: media
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-bind-password
  namespace: media
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/lldap-secrets
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-api-key
  namespace: media
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: api-key
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "homepage"
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-api-key
  namespace: media
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: api-key
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "homepage"
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-api-key
  namespace: media
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: api-key
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "homepage"
data: { }
