---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-oidc-client-secret
  namespace: mealie
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/mealie-oidc-client-secret
data: { }
