---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-db-credentials
  namespace: mealie
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/mealie-role-password
type: Opaque
data: { }
