---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: cloudflare-api-token
  data:
    - secretKey: token
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/cloudflare-api-token
        property: token
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-public-ip
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: cluster-public-ip
  data:
    - secretKey: ip
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/public-ip
        property: ip
