{
 "title": "Jellyfin",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Content", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_total", "legendFormat": "movie" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_series_total", "legendFormat": "series" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_total", "legendFormat": "episode" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_artists_total", "legendFormat": "artist" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_albums_total", "legendFormat": "album" }
   ]
  },
  {
   "title": "Size on Disk",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_filesize_total{}", "legendFormat": "movies" },
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "series" },
    { "expr": "lidarr_artists_filesize_bytes", "legendFormat": "music" },
    {
     "expr": "radarr_rootfolder_freespace_bytes",
     "legendFormat": "free"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_missing_total", "legendFormat": "missing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_missing_total", "legendFormat": "missing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lidarr_albums_missing_total", "legendFormat": "missing" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_queue_total) by (download_state, download_status)",
     "legendFormat": "{{download_state}} - {{download_status}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_queue_total) by (download_state, download_status)",
     "legendFormat": "{{download_state}} - {{download_status}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lidarr_queue_total) by (download_state, download_status)",
     "legendFormat": "{{download_state}} - {{download_status}}"
    }
   ]
  },
  { "title": "Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyfin_stream_count) by (username)",
     "legendFormat": "Streams"
    }
   ]
  },
  {
   "title": "Stream Time by User",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\r\n  (\r\n    sum by (username) (sum without() (jellyfin_stream_count{}))\r\n  )[$__range:1m]\r\n) ",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(jellyfin_stream_count) by (username)",
     "legendFormat": "{{username}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "jellyfin_stream_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transmit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"media\", pod=~\"jellyfin-app.*\"}[2m])) / 8 / 10000 ",
     "legendFormat": "jellyfin"
    },
    {
     "expr": "unpoller_site_transmit_rate_bytes{subsystem=\"wan\"} / 8 / 10000 / 4",
     "legendFormat": "wan"
    },
    {
     "expr": "unpoller_device_speedtest_upload",
     "legendFormat": "speed test"
    }
   ]
  },
  {
   "title": "Device Type",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyfin_connected_clients_count) by (device)",
     "legendFormat": "{{play_method}}"
    }
   ]
  },
  {
   "title": "Play Method",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyfin_stream_count) by (play_method)",
     "legendFormat": "{{play_method}}"
    }
   ]
  },
  {
   "title": "Client Type",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyfin_connected_clients_count) by (client)",
     "legendFormat": "{{play_method}}"
    }
   ]
  }
 ]
}