---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/values.schema.json
# https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
controllers:
  gotenberg:
    type: deployment
    replicas: 1

    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

    containers:
      app:
        image:
          repository: gotenberg/gotenberg
          # renovate: datasource=docker depName=gotenberg packageName=gotenberg/gotenberg
          tag: "${gotenberg_version}"
        args:
          - gotenberg
          - --chromium-disable-javascript=true
          - --chromium-allow-list=file:///tmp/.*
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 1Gi
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: 3000
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: 3000
              periodSeconds: 10

service:
  app:
    controller: gotenberg
    ports:
      http:
        port: 3000
