---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-internal
  namespace: immich
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Immich"
    gethomepage.dev/group: "Apps"
    gethomepage.dev/icon: "immich.svg"
    gethomepage.dev/widget.type: "immich"
    gethomepage.dev/widget.url: "http://immich-server.immich.svc:2283"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=server"
spec:
  parentRefs:
    - name: internal
      namespace: istio-gateway
  hostnames:
    - "immich.${internal_domain}"
  rules:
    - backendRefs:
        - name: immich-server
          port: 2283
