---
apiVersion: v1
kind: Secret
metadata:
  name: freshrss-oidc-crypto-key
  namespace: freshrss
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: crypto-key
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "32"
type: Opaque
data: { }
