---
apiVersion: v1
kind: Secret
metadata:
  name: freshrss-db-credentials
  namespace: freshrss
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/freshrss-role-password
type: Opaque
data: { }
