---
apiVersion: v1
kind: Namespace
metadata:
  name: freshrss
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
    network-policy.homelab/profile: internal-egress
    access.network-policy.homelab/postgres: "true"
