---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-config
data:
  config.yaml: |
    metrics:
      - name: cluster_uptime
        query: kromgo:cluster_uptime_days:instant
        suffix: " days"
        colors:
          - { color: "red", min: 0, max: 7 }
          - { color: "yellow", min: 7, max: 30 }
          - { color: "green", min: 30, max: 9999 }

      - name: node_count
        query: kromgo:node_count:instant
        suffix: " nodes"
        colors:
          - { color: "green", min: 1, max: 9999 }

      - name: pod_count
        query: kromgo:pod_count:instant
        suffix: " pods"
        colors:
          - { color: "green", min: 1, max: 9999 }

      - name: cluster_cpu_usage
        query: kromgo:cluster_cpu_usage_percent:instant
        suffix: "%"
        colors:
          - { color: "green", min: 0, max: 50 }
          - { color: "yellow", min: 50, max: 80 }
          - { color: "red", min: 80, max: 100 }

      - name: cluster_memory_usage
        query: kromgo:cluster_memory_usage_percent:instant
        suffix: "%"
        colors:
          - { color: "green", min: 0, max: 50 }
          - { color: "yellow", min: 50, max: 80 }
          - { color: "red", min: 80, max: 100 }

      - name: kubernetes_version
        query: kromgo:kubernetes_version_info:instant
        label: git_version
        colors:
          - { color: "blue", min: 0, max: 0 }
