---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyseerr-internal
  namespace: media
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Jellyseerr"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "jellyseerr.svg"
    gethomepage.dev/widget.type: "jellyseerr"
    gethomepage.dev/widget.url: "http://jellyseerr.media.svc:5055"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=jellyseerr"
spec:
  parentRefs:
    - name: internal
      namespace: istio-gateway
  hostnames:
    - "requests.${internal_domain}"
  rules:
    - backendRefs:
        - name: jellyseerr
          port: 5055
