---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - canary-jfa-go.yaml
  - canary-jellyfin.yaml
  - canary-jellyseerr.yaml
  - canary-vpn-health.yaml
  - media-auth-policy.yaml
  - jellyfin-dashboard.yaml
  - prometheus-rules.yaml
  - exportarr-alerts.yaml
