---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prowlarr-internal
  namespace: media
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Prowlarr"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "prowlarr.svg"
    gethomepage.dev/widget.type: "prowlarr"
    gethomepage.dev/widget.url: "http://prowlarr.media.svc:9696"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=prowlarr"
spec:
  parentRefs:
    - name: internal
      namespace: istio-gateway
  hostnames:
    - "prowlarr.${internal_domain}"
  rules:
    - backendRefs:
        - name: prowlarr
          port: 9696
