---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr4k-internal
  namespace: media
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Radarr 4K"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "radarr.svg"
    gethomepage.dev/widget.type: "radarr"
    gethomepage.dev/widget.url: "http://radarr4k-app.media.svc:7878"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_RADARR4K_API_KEY}}"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=radarr4k"
spec:
  parentRefs:
    - name: internal
      namespace: istio-gateway
  hostnames:
    - "radarr4k.${internal_domain}"
  rules:
    - backendRefs:
        - name: radarr4k
          port: 7878
