{
 "title": "Loki Kubernetes Logs",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   { "name": "container", "query": "label_values(container)" },
   { "name": "stream", "query": "label_values(stream)" }
  ]
 },
 "panels": [
  { "title": "Visualizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs by App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (app) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", container =~\"$container\", stream=~\"$stream\", node_name!=\"\"} |~ \"$query\" [$__range]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Logs by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (node_name) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", container =~\"$container\", stream=~\"$stream\", node_name!=\"\"} |~ \"$query\" [$__range]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", app=~\"$app\", container =~\"$container\", stream=~\"$stream\", node_name!=\"\"} |= \"$query\" [$__interval]))",
     "legendFormat": "Log count"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", app=~\"$app\", container =~\"$container\", stream=~\"$stream\", node_name!=\"\"} |= \"$query\""
    }
   ]
  }
 ]
}