{
 "title": "Harvester Cluster Logs",
 "description": "Logs collected from Kubernetes, stored in Loki",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query", "label": "Search Query" },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   },
   {
    "name": "pod",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Visualizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs by App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (count_over_time({host!=\"\",namespace=~\"$namespace\", pod=~\"$pod\",container=~\"$container\"} |= \"$query\" [$__range]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Logs by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (host) (count_over_time({host!=\"\",namespace=~\"$namespace\", pod=~\"$pod\",container=~\"$container\"} |= \"$query\" [$__range]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({host!=\"\",namespace=~\"$namespace\", pod=~\"$pod\",container=~\"$container\"} |= \"$query\" [$__interval]))",
     "legendFormat": "Log count"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{host!=\"\",namespace=~\"$namespace\", pod=~\"$pod\",container=~\"$container\"} |= \"$query\""
    }
   ]
  }
 ]
}