---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: cnpg-platform-s3
spec:
  clusterRef:
    name: garage
  bucketPermissions:
    - bucketRef:
        name: cnpg-platform-backups
      read: true
      write: true
  secretTemplate:
    name: cnpg-platform-s3-credentials
    namespace: database
