---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: cnpg-platform-backups
spec:
  clusterRef:
    name: garage
  quotas:
    maxSize: "50Gi"
  keyPermissions:
    - keyRef:
        name: cnpg-platform-s3
      read: true
      write: true
