---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: cnpg-immich-backups
spec:
  clusterRef:
    name: garage
  quotas:
    maxSize: "50Gi"
  keyPermissions:
    - keyRef: cnpg-immich-s3
      read: true
      write: true
