---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hass-google-caldav-secret
  namespace: home-assistant
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: hass-google-caldav-secret
    template:
      engineVersion: v2
      data:
        secrets.yaml: |
          google_caldav_email: "{{ .email }}"
          google_caldav_password: "{{ .appPassword }}"
  data:
    - secretKey: email
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/hass-google-caldav/email
    - secretKey: appPassword
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/hass-google-caldav/app-password
