---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 10Gi
