---
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-oidc-client-secret
  namespace: home-assistant
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/home-assistant-oidc-client-secret
data: { }
