---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: dr-test-s3
  namespace: garage
spec:
  clusterRef:
    name: garage
  bucketPermissions:
    - bucketRef: dr-test
      read: true
      write: true
  secretTemplate:
    name: dr-test-s3-credentials
    namespace: garage
