---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-db-credentials
  namespace: authelia
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/authelia-role-password
type: kubernetes.io/basic-auth
data: { }
