---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-db-credentials
  namespace: authelia
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/lldap-role-password
type: Opaque
data: { }
