---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vaultwarden-admin-token.yaml
  - vaultwarden-db-credentials.yaml
  - internal-route.yaml
  - external-route.yaml
  - canary.yaml
