---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-db-credentials
  namespace: vaultwarden
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/vaultwarden-role-password
type: kubernetes.io/basic-auth
data: { }
