---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-oidc-client-secret
  namespace: vaultwarden
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/vaultwarden-oidc-client-secret
data: { }
