{
 "title": "Hardware Status",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instances", "query": { "query": "ipmi_bmc_info" } }
  ]
 },
 "panels": [
  { "title": "$instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instances" },
  {
   "title": "IPMI Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayType": "Regular",
     "expr": "ipmi_bmc_info{instance=~\"$instances\"}",
     "legendFormat": "__auto",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayType": "Regular",
     "expr": "ipmi_chassis_power_state{instance=~\"$instances\"}",
     "legendFormat": "__auto",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cooling",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayType": "Regular",
     "expr": "ipmi_chassis_cooling_fault_state{instance=~\"$instances\"}",
     "legendFormat": "__auto",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Drives",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayType": "Regular",
     "expr": "ipmi_chassis_drive_fault_state{instance=~\"$instances\"}",
     "legendFormat": "__auto",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{instance=\"$instances\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temp (c)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$instances\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_sensor_state{instance=~\"$instances\", type=\"Power Supply\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_sensor_state{instance=~\"$instances\", type=\"Drive Slot\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_sensor_state{instance=~\"$instances\", type=\"Physical Security\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}