---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: paperless
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secret-key
    secret-generator.v1.mittwald.de/length: "64"
    secret-generator.v1.mittwald.de/encoding: base64
data: { }
