---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-oidc-client-secret
  namespace: paperless
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/paperless-oidc-client-secret
data: { }
