---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-db-credentials
  namespace: paperless
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/paperless-role-password
type: kubernetes.io/basic-auth
data: { }
