---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: papra
  namespace: papra
spec:
  clusterRef:
    name: garage
    namespace: garage
  neverExpires: true
  bucketPermissions:
    - bucketRef:
        name: papra
        namespace: garage
      read: true
      write: true
  secretTemplate:
    name: papra-s3-credentials
