---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-healthchecks-api-key
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: homepage-healthchecks-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/homepage/healthchecks-api-key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-immich-api-key
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: homepage-immich-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/homepage/immich-api-key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-paperless-api-key
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: homepage-paperless-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/homepage/paperless-api-key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-jellyseerr-api-key
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: homepage-jellyseerr-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/homepage/jellyseerr-api-key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-bazarr-api-key
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: homepage-bazarr-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/homepage/bazarr-api-key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-grafana-api-key
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: homepage-grafana-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/homepage/grafana-api-key
