---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-api-key
  namespace: homepage
  annotations:
    replicator.v1.mittwald.de/replicate-from: media/sonarr-api-key
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-api-key
  namespace: homepage
  annotations:
    replicator.v1.mittwald.de/replicate-from: media/radarr-api-key
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-api-key
  namespace: homepage
  annotations:
    replicator.v1.mittwald.de/replicate-from: media/prowlarr-api-key
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-api-token
  namespace: homepage
  annotations:
    replicator.v1.mittwald.de/replicate-from: media/jellyfin-exporter-api-token
data: { }
