---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: flux-system
spec:
  dependsOn:
    - name: cloudnative-pg
    - name: secret-generator
  chart:
    spec:
      chart: app-template
      version: "${app_template_version}"
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: paperless
  install:
    createNamespace: false
    strategy:
      name: RetryOnFailure
    timeout: 10m
  interval: 10m
  maxHistory: 3
  releaseName: paperless
  targetNamespace: paperless
  uninstall:
    keepHistory: false
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
    timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: paperless-values
      valuesKey: values.yaml
