---
apiVersion: v1
kind: Secret
metadata:
  name: palworld-server-password
  namespace: palworld
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/length: "16"
    secret-generator.v1.mittwald.de/encoding: hex
data: { }
---
apiVersion: v1
kind: Secret
metadata:
  name: palworld-admin-password
  namespace: palworld
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/length: "32"
    secret-generator.v1.mittwald.de/encoding: hex
data: { }
