---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - open-webui-oidc-client-secret.yaml
  - open-webui-db-credentials.yaml
  - cnpg-superuser-replica.yaml
  - dragonfly-secret-replication.yaml
  - network-policy.yaml
