---
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-oidc-client-secret
  namespace: ai
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/open-webui-oidc-client-secret
data: { }
