---
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-oidc-client-secret
  namespace: authelia
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: client-secret
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/length: "64"
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "ai"
data: { }
