---
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-db-credentials
  namespace: ai
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/open-webui-role-password
type: kubernetes.io/basic-auth
data: { }
