---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/longhorn.io/setting_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
  namespace: longhorn-system
value: s3://homelab-longhorn-backup-${cluster_name}@us-east-2/
