---
apiVersion: v1
kind: Secret
metadata:
  name: firefly-db-credentials
  namespace: firefly
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/firefly-role-password
type: Opaque
data: { }
