---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-app-key
  namespace: firefly
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: firefly-app-key
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: /homelab/kubernetes/${cluster_name}/firefly/app-key
