---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - firefly-db-credentials.yaml
  - firefly-app-key.yaml
  - firefly-upload-pvc.yaml
  - internal-route.yaml
  - external-route.yaml
