---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: tandoor
  namespace: garage
spec:
  clusterRef:
    name: garage
  keyPermissions:
    - keyRef:
        name: tandoor
        namespace: tandoor
      read: true
      write: true
