---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: tandoor
  namespace: tandoor
spec:
  clusterRef:
    name: garage
    namespace: garage
  neverExpires: true
  bucketPermissions:
    - bucketRef:
        name: tandoor
        namespace: garage
      read: true
      write: true
  secretTemplate:
    name: tandoor-s3-credentials
