---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: tandoor
  namespace: garage
spec:
  clusterRef:
    name: garage
  neverExpires: true
  bucketPermissions:
    - bucketRef:
        name: tandoor
      read: true
      write: true
  secretTemplate:
    name: tandoor-s3-credentials
    namespace: tandoor
