---
apiVersion: v1
kind: Secret
metadata:
  name: tandoor-secret
  namespace: tandoor
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: SECRET_KEY
    secret-generator.v1.mittwald.de/length: "64"
    secret-generator.v1.mittwald.de/encoding: hex
data: { }
