---
apiVersion: v1
kind: Secret
metadata:
  name: tandoor-oidc-client-secret
  namespace: tandoor
  annotations:
    replicator.v1.mittwald.de/replicate-from: authelia/tandoor-oidc-client-secret
data: { }
