---
apiVersion: v1
kind: Secret
metadata:
  name: tandoor-db-credentials
  namespace: tandoor
  annotations:
    replicator.v1.mittwald.de/replicate-from: database/tandoor-role-password
type: kubernetes.io/basic-auth
data: { }
